Modified assemble script

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -7,80 +7,75 @@
 
 set -e
 
-# FIXME: Linking of global modules is disabled for now as it causes npm failures
-#        under RHEL7
-# Global modules good to have
-# npmgl=$(grep "^\s*[^#\s]" ../etc/npm_global_module_list | sort -u)
-# Available global modules; only match top-level npm packages
-#global_modules=$(npm ls -g 2> /dev/null | perl -ne 'print "$1\n" if /^\S+\s(\S+)\@[\d\.-]+/' | sort -u)
-# List all modules in common
-#module_list=$(/usr/bin/comm -12 <(echo "${global_modules}") | tr '\n' ' ')
-# Link the modules
-#npm link $module_list
+LOCAL_SOURCE_DIR=/tmp/src
+DEPLOY_DIR=${HOME}
+PACKAGE_NAME = ${NODEJS_PACKAGE_NAME}
+IS_SCOPED_PACKAGE = ${NODEJS_IS_SCOPED_PACKAGE}
 
-
-safeLogging () {
-    if [[ $1 =~ http[s]?://.*@.*$ ]]; then
-        echo $1 | sed 's/^.*@/redacted@/'
-    else
-        echo $1
-    fi
+function copy_artifacts() {
+  if [ -d $LOCAL_SOURCE_DIR/$1 ]; then
+    echo "Copying all package elements from $LOCAL_SOURCE_DIR/$1 directory into $DEPLOY_DIR for later deployment..."
+    cp -v $LOCAL_SOURCE_DIR/$1/* $DEPLOY_DIR 2> /dev/null
+  fi
 }
 
+function remove_elements() {
+    if [ -d $LOCAL_SOURCE_DIR/package ]; then
+        echo "Removing uncompressed elements"
+        rm -rf $LOCAL_SOURCE_DIR/package
+    fi
+
+    echo "Removing tarball"
+    rm -f $LOCAL_SOURCE_DIR/*.tgz
+}
+
+
 shopt -s dotglob
-echo "Before assembling"
-
-    echo "---> KEEDIO ************** Installing application source ..."
-    echo "pwd:"
-    pwd
-    echo "node version:"
-    node --version
-    echo "npm version:"
-    npm --version
-    echo "ls -al /tmp/src"
-    ls -al /tmp/src
-    echo "ls /usr/libexec/s2i/assemble:"
-    ls -al /usr/libexec/s2i
-    echo "echo $HOME"
-    echo $HOME
 
 
-    echo "npm config get registry"
-    npm config get registry
+echo "---> ************** (PRE ASSEMBLE) "
 
-    echo "cd /tmp/src"
-    cd /tmp/src
-    echo "ls -al"
-    ls -al
-    echo "npm view keedio-nodejs-helloworld  dist.tarball"
-    npm view keedio-nodejs-helloworld  dist.tarball
-    echo "npm pack keedio-nodejs-helloworld@1.0.2"
-    npm pack keedio-nodejs-helloworld@1.0.2
-    echo "ls -al"
-    ls -al
+echo "---> Node version"
+node --version
 
+echo "---> NPM version"
+npm --version
 
-    echo "tar -xvzf keedio-nodejs-helloworld-1.0.2.tgz"
-    tar -xvzf keedio-nodejs-helloworld-1.0.2.tgz
+echo "---> Registry location"
+npm config get registry
 
-    echo "mv package/* /opt/app-root/src"
-    mv package/* /opt/app-root/src
+cd "$LOCAL_SOURCE_DIR"
 
-    echo "rm -rf package"
-    rm -rf package
+echo "---> NPM view tarball"
+npm view $PACKAGE_NAME dist.tarball
 
-    echo "rm -rf keedio-nodejs-helloworld-1.0.2.tgz"
-    rm -rf keedio-nodejs-helloworld-1.0.2.tgz
+echo "---> NPM get tarball"
+npm pack $PACKAGE_NAME
 
-    echo "cd"
-    cd
+echo "---> tar artifact"
+tar -xvzf keedio-nodejs-helloworld-1.0.2.tgz
 
+ERR=$?
 
+if [ $ERR -ne 0 ]; then
+    echo "Aborting due to error code $ERR from tar"
+    exit $ERR
+fi
+
+if [ -d "$LOCAL_SOURCE_DIR/package" ]; then
+    #Copying module elements
+    copy_artifacts "package"
+else
+    echo "Aborting due to error code 1 from copying module elements"
+    exit 1
+fi
+
+#Removing elements
+remove_elements
+
+#Change to $HOME
+cd $HOME
 
 
 echo "Executing original assembling"
-
 /usr/libexec/s2i/assemble
-
-# Fix source directory permissions
-fix-permissions ./
