Modified assemble script

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -6,9 +6,6 @@
 [ -d "/usr/src/app" ] && exit 0
 
 
-
-
-
 function copy_artifacts() {
   if [ -d $LOCAL_SOURCE_DIR/$1 ]; then
     echo "Copying all package elements from $LOCAL_SOURCE_DIR/$1 directory into $DEPLOY_DIR for later deployment..."
@@ -38,31 +35,27 @@ date
 
 LOCAL_SOURCE_DIR=/tmp/src
 DEPLOY_DIR=${HOME}
-PACKAGE_TAG = $NODEJS_PACKAGE_TAG
-PACKAGE_TARBALL = $NODEJS_PACKAGE_TARBALL
-IS_SCOPED_PACKAGE = $NODEJS_IS_SCOPED_PACKAGE
 
 echo "Pre assemble parameters"
 echo "LOCAL_SOURCE_DIR: $LOCAL_SOURCE_DIR"
 echo "DEPLOY_DIR: $DEPLOY_DIR"
 echo "NODEJS_PACKAGE_TAG: ${NODEJS_PACKAGE_TAG}"
-echo "NODEJS_PACKAGE_TARBALLG: ${NODEJS_PACKAGE_TAG}"
-echo "IS_SCOPED_PACKAGE: $IS_SCOPED_PACKAGE"
-
-echo ${NODEJS_PACKAGE_TAG}
-echo ${NODEJS_PACKAGE_TARBALL}
-echo env.NODEJS_PACKAGE_TAG
-
-
+echo "NODEJS_PACKAGE_TARBALL: ${NODEJS_PACKAGE_TARBALL}"
+echo "IS_SCOPED_PACKAGE: ${NODEJS_IS_SCOPED_PACKAGE}"
 
 if [ -z "${NODEJS_PACKAGE_TAG}" ]; then
-    echo "Aborting due to PACKAGE_TAG environment variable is not setted"
-    exit 0
+    echo "Aborting due to NODEJS_PACKAGE_TAG environment variable is not setted"
+    exit 1
 fi
 
-if [ -z "$PACKAGE_TARBALL" ]; then
-    echo "Aborting due to PACKAGE_TARBALL environment variable is not setted"
-    exit 0
+if [ -z "${NODEJS_PACKAGE_TARBALL}" ]; then
+    echo "Aborting due to NODEJS_PACKAGE_TARBALL environment variable is not setted"
+    exit 1
+fi
+
+if [ -z "${NODEJS_IS_SCOPED_PACKAGE}" ]; then
+    echo "Aborting due to NODEJS_IS_SCOPED_PACKAGE environment variable is not setted"
+    exit 1
 fi
 
 echo "---> Node version"
@@ -77,13 +70,13 @@ npm config get registry
 cd "$LOCAL_SOURCE_DIR"
 
 echo "---> NPM view tarball"
-npm view $PACKAGE_TAG dist.tarball
+npm view ${NODEJS_PACKAGE_TAG} dist.tarball
 
 echo "---> NPM get tarball"
-npm pack $PACKAGE_TAG
+npm pack ${NODEJS_PACKAGE_TAG}
 
 echo "---> tar artifact"
-tar -xvzf $PACKAGE_TARBALL
+tar -xvzf ${NODEJS_PACKAGE_TARBALL}
 
 ERR=$?
 
