Modified assemble script

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -43,6 +43,8 @@ echo "NODEJS_PACKAGE_TAG: ${NODEJS_PACKAGE_TAG}"
 echo "NODEJS_PACKAGE_TARBALL: ${NODEJS_PACKAGE_TARBALL}"
 echo "IS_SCOPED_PACKAGE: ${NODEJS_IS_SCOPED_PACKAGE}"
 echo "ARTIFACTORY_NPM_REPO: ${ARTIFACTORY_NPM_REPO}"
+echo "NPM_AUTH: ${NPM_AUTH}"
+echo "NPM_EMAIL_AUTH: ${NPM_EMAIL_AUTH}"
 
 if [ -z "${NODEJS_PACKAGE_TAG}" ]; then
     echo "Aborting due to NODEJS_PACKAGE_TAG environment variable is not setted"
@@ -59,6 +61,8 @@ if [ -z "${NODEJS_IS_SCOPED_PACKAGE}" ]; then
     exit 1
 fi
 
+
+
 echo "---> Node version"
 node --version
 
@@ -66,32 +70,30 @@ echo "---> NPM version"
 npm --version
 
 
-
-
-
-export NPM_AUTH="amNmZXJuYW5kZXo6QVA2MnhVWkpBRWQ4VGF4NW5WdDJSOE1Ib2FH"
-
-
-echo "/tmp/src/.npmrc"
-cat /tmp/src/.npmrc
+export NPM_AUTH=${NPM_AUTH}
+export NPM_AUTH_EMAIL=${NPM_EMAIL_AUTH}
 
 if [ -z "${ARTIFACTORY_NPM_REPO}" ]; then
     echo "ARTIFACTORY_NPM_REPO variable is not setted "
 else
     echo "---> Setting Artifactory NPM Registry location"
     npm config set registry  ${ARTIFACTORY_NPM_REPO}
+
+    if [ -z "${NPM_AUTH}" ]; then
+        echo "Aborting due to NPM_AUTH environment variable is not setted"
+        exit 1
+    fi
+
+    if [ -z "${NPM_EMAIL_AUTH}" ]; then
+        echo "Aborting due to NPM_EMAIL_AUTH environment variable is not setted"
+        exit 1
+    fi
 fi
 
 echo "---> NPM Registry location"
 npm config get registry
 
 cd "$LOCAL_SOURCE_DIR"
-
-
-echo "/opt/app-root/src/.npmrc"
-cat /opt/app-root/src/.npmrc
-
-
 
 
 echo "---> NPM view tarball"
