Modified assemble script

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -49,6 +49,16 @@ echo "PACKAGE_TARBALL: $PACKAGE_TARBALL"
 echo "IS_SCOPED_PACKAGE: $IS_SCOPED_PACKAGE"
 
 
+if [ -z "$PACKAGE_TAG" ]; then
+    echo "Aborting due to PACKAGE_TAG environment variable is not setted"
+    exit 1
+fi
+
+if [ -z "$PACKAGE_TARBALL" ]; then
+    echo "Aborting due to PACKAGE_TARBALL environment variable is not setted"
+    exit 1
+fi
+
 echo "---> Node version"
 node --version
 
